version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0    
    container_name: mysql_db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - node-network         

networks:
  node-network:
    driver: bridge

    
