version: '3'

services:
  app:
    build: 
      context: node
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"


  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0    
    container_name: mysql_db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network         

networks:
  node-network:
    driver: bridge

    
